### ISSUE TITLE
Create mobile style

### ISSUE THREAD

**Issue by smit1678** [hotosm/matomo-tracking#5]
Font and size seems a little large for mobile. Could use a review to see how we can optimize on mobile. 

![32ba2ccc-f335-4a8d-ab64-3e5cf02d4f7a](https://user-images.githubusercontent.com/796838/50783380-a1085780-12e5-11e9-9b98-caf7d1cf7593.png)

**Comment by dakotabenjamin** [comment]
Here's what I've got: 
![image](https://user-images.githubusercontent.com/1847818/50853532-77d0e100-1350-11e9-8ade-3c8ee0041f41.png)

**Comment by dakotabenjamin** [comment]
It reduces a lot of padding/margins and makes the font size 1em -> 0.8em

**Comment by dakotabenjamin** [comment]
https://github.com/hotosm/matomo-tracking/commit/64aa4efe9a38dff37500e23b4b42699966dd656f

**Comment by smit1678** [comment]
👍 Great, I think this works a lot better.
