### ISSUE TITLE
Creating/documenting advanced options

### ISSUE THREAD

**Issue by smit1678** [hotosm/matomo-tracking#7]
As we look to use the new Matomo version across our tools more, there are a few events and more advanced tracking that would be helpful to have documented/enable for use: 

* Tracking clicks/downloads on files, like a PDF report https://matomo.org/faq/new-to-piwik/faq_47/
* Specific content tracking (interacting with a banner or specific element on a page) https://matomo.org/docs/content-tracking/
* Creating funnels for specific actions, like conversion rate of users logging into Export Tool and then creating downloading a file. 

@dakotabenjamin Can you look into these and either see if we just need a quick training and write some docs, or if we need to do some additional html/js work to implement some of these things. To make item 1 actionable, this is related to specific PDFs on hotosm.org and tracking downloads on the documentation site template.

**Comment by dakotabenjamin** [comment]
I added some docs explaining how simple it is to track specific content: https://github.com/hotosm/matomo-tracking/blob/master/docs/tracking-content.md and pushed some examples of this use to hotosm-website (https://github.com/hotosm/hotosm-website/pull/566)

To the third point, I think we can build some advanced content tracking with javascript but it may require special code in the tracking script itself, making it difficult to use the generic script we are using now. Let's make that into a new issue to outline some possible use cases to try.
