### ISSUE TITLE
Improve geolocation

### ISSUE THREAD

**Issue by smit1678** [hotosm/matomo-tracking#8]
Right now our geolocation tracking seems to be off. On our previous Piwik, it shows me in Indonesia (which is correct). But with new Matomo instance, it shows me in United States.

**Comment by dakotabenjamin** [comment]
I enabled the GeoIP database in the matomo settings. Please check again and see if it shows your correct location.

**Comment by smit1678** [comment]
👍 Looks like it's working well.
